2024-11-08 09:24:40,042 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 09:37:30,822 - application_logger - DEBUG - Calling get_token in views.py with args: (<class 'base.views.MyTokenObtainPairSerializer'>, <User: coral>), kwargs: {} | User ID: 123 | Object ID: 456
2024-11-08 09:37:30,833 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-08 09:37:30,888 - application_logger - DEBUG - Calling list_by_user in views.py with args: (<base.views.GroupListViewSet object at 0x10389c680>, <rest_framework.request.Request: GET '/grouplists/by-user/1/'>), kwargs: {'user_id': '1'} | User ID: 123 | Object ID: 456
2024-11-08 09:37:30,896 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-08 09:37:51,668 - application_logger - DEBUG - Calling list_by_user in views.py with args: (<base.views.GroupListViewSet object at 0x1037ffda0>, <rest_framework.request.Request: GET '/grouplists/by-user/1/'>), kwargs: {'user_id': '1'} | User ID: 123 | Object ID: 456
2024-11-08 09:37:51,679 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-08 10:54:23,363 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:23,984 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:35,390 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:35,780 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:37,968 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:38,194 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:40,326 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:40,554 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:47,877 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:48,093 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:52,299 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:52,499 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:56,717 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:56,959 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:54:59,112 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:54:59,330 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:01,489 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:01,689 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:03,837 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:04,151 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:07,362 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:07,585 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:11,788 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:12,088 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:16,307 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:16,614 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:20,989 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:21,252 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:28,565 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:28,833 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:31,043 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:31,261 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:55:39,592 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py changed, reloading.
2024-11-08 10:55:39,840 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:56:47,962 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-08 10:56:48,441 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:57:01,921 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-08 10:57:02,287 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:57:04,472 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-08 10:57:04,757 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:15,553 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:15,941 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:21,214 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:21,432 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:22,589 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:22,853 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:25,022 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:25,254 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:27,398 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:27,627 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:40,060 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:40,423 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:43,652 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 10:58:43,883 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:58:58,390 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/urls.py changed, reloading.
2024-11-08 10:58:58,863 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:59:03,007 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/urls.py changed, reloading.
2024-11-08 10:59:03,224 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:59:14,624 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/urls.py changed, reloading.
2024-11-08 10:59:14,975 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:59:18,195 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/urls.py changed, reloading.
2024-11-08 10:59:18,447 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 10:59:23,713 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/urls.py changed, reloading.
2024-11-08 10:59:23,949 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-08 11:01:11,735 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/myproj/settings.py changed, reloading.
2024-11-08 11:01:12,112 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:20:22,252 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:20:22,811 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:32:26,448 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:34:01,090 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:34:01,500 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:34:02,649 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:34:02,882 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:34:06,038 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:34:06,214 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:34:07,355 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:34:07,608 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:35:28,894 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:35:29,214 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:35:33,377 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:35:33,599 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:36:17,863 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:36:18,254 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:36:20,405 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:36:20,658 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:36:25,959 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:36:26,203 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:36:31,464 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/models.py changed, reloading.
2024-11-10 08:36:31,706 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 08:39:09,601 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:33:00,538 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:33:00,602 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:33:47,039 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:33:52,711 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:34:52,005 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:45:19,878 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:45:19,928 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:46:49,054 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:46:49,118 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:48:15,809 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:48:15,865 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:50:57,620 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:50:57,667 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:53:17,037 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:53:17,095 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:53:26,814 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:53:26,916 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x1030a3e00>.
2024-11-10 09:55:11,441 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:55:12,029 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:55:50,230 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:55:50,574 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:55:59,949 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:00,289 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:06,456 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:06,792 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:12,031 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:12,401 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:14,583 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:14,828 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:17,998 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:18,251 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:19,380 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:19,622 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:20,784 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 09:56:21,092 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 09:56:24,556 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:56:24,612 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x1069e6330>.
2024-11-10 09:58:26,614 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:58:26,651 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:58:36,155 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:58:36,201 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x106a587a0>.
2024-11-10 09:58:46,812 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:58:46,989 - django.request - WARNING - Not Found: /favicon.ico
2024-11-10 09:59:42,614 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:59:42,664 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:59:53,027 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 09:59:53,075 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x106c86180>.
2024-11-10 10:00:04,771 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:01:00,288 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:01:00,699 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:01:06,529 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:03:53,066 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:04:45,872 - django.request - WARNING - Unauthorized: /listitem/1/
2024-11-10 10:06:00,865 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:06:00,871 - django.request - WARNING - Bad Request: /listitem/1/
2024-11-10 10:06:16,918 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:06:16,924 - django.request - WARNING - Bad Request: /listitem/1/
2024-11-10 10:07:20,126 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:07:20,186 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 41, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x107f91f40>.
2024-11-10 10:07:48,966 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:07:49,004 - django.request - ERROR - Internal Server Error: /listitem/1/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 41, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x109096360>.
2024-11-10 10:20:21,996 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:22,036 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:34,540 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:34,567 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:34,615 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:47,215 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:20:47,281 - django.request - ERROR - Internal Server Error: /listitem/4/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 41, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x1090e7e90>.
2024-11-10 10:22:21,890 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:22:22,639 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:22:24,290 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:22:24,295 - application_logger - ERROR - Error in perform_update: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108f5f530>. | User ID: 123 | Object ID: 456
2024-11-10 10:22:24,329 - django.request - ERROR - Internal Server Error: /listitem/4/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108f5f530>.
2024-11-10 10:22:53,292 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:22:53,390 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:22:57,407 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:23:00,785 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:23:04,218 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:23:04,227 - application_logger - ERROR - Error in perform_update: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108ff5280>. | User ID: 123 | Object ID: 456
2024-11-10 10:23:04,286 - django.request - ERROR - Internal Server Error: /listitem/4/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108ff5280>.
2024-11-10 10:23:32,093 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:24:10,833 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:24:10,873 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:24:15,987 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:24:15,993 - application_logger - ERROR - Error in perform_update: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108e98d70>. | User ID: 123 | Object ID: 456
2024-11-10 10:24:16,034 - django.request - ERROR - Internal Server Error: /listitem/3/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108e98d70>.
2024-11-10 10:27:15,382 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:27:15,443 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:27:19,347 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:27:19,353 - application_logger - ERROR - Error in perform_update: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108ff7b90>. | User ID: 123 | Object ID: 456
2024-11-10 10:27:19,402 - django.request - ERROR - Internal Server Error: /listitem/3/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108ff7b90>.
2024-11-10 10:35:19,790 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:35:19,854 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:35:27,219 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:35:40,607 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:35:40,612 - application_logger - ERROR - Error in perform_update: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108fbb4d0>. | User ID: 123 | Object ID: 456
2024-11-10 10:35:40,689 - django.request - ERROR - Internal Server Error: /listitem/3/
Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/contrib/auth/models.py", line 438, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 68, in update
    self.perform_update(serializer)
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/logging_utils.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py", line 42, in perform_update
    serializer.save(user_id=self.request.user)  # שמירת user_id של המשתמש המחובר
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 203, in save
    self.instance = self.update(self.instance, validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/rest_framework/serializers.py", line 1033, in update
    instance.save()
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 891, in save
    self.save_base(
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 997, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1129, in _save_table
    updated = self._do_update(
              ^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/base.py", line 1194, in _do_update
    return filtered._update(values) > 0
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/query.py", line 1278, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 2003, in execute_sql
    cursor = super().execute_sql(result_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1561, in execute_sql
    sql, params = self.as_sql()
                  ^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1966, in as_sql
    val = field.get_db_prep_save(val, connection=self.connection)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/related.py", line 1142, in get_db_prep_save
    return self.target_field.get_db_prep_save(value, connection=connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 1008, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2815, in get_db_prep_value
    value = self.get_prep_value(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/coralingber/Desktop/untitled folder 2/lista/backend/env/lib/python3.12/site-packages/django/db/models/fields/__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x108fbb4d0>.
2024-11-10 10:39:53,131 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:39:53,648 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:39:54,808 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:39:55,052 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:44:04,869 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:44:05,240 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:44:21,972 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:44:22,411 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:44:26,634 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:44:26,910 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:44:34,188 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:44:34,454 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:45:11,530 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:45:11,992 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:45:47,027 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:45:47,553 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:46:51,762 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:47:12,915 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:13,006 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:22,424 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:22,445 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:22,482 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:41,905 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:47:41,915 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 10:47:41,917 - django.request - WARNING - Forbidden: /listitem/3/
2024-11-10 10:48:07,456 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:48:07,462 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 10:48:07,462 - django.request - WARNING - Forbidden: /listitem/3/
2024-11-10 10:49:57,885 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:50:02,676 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:50:02,692 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:50:02,732 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:50:07,168 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:50:07,174 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 10:50:07,176 - django.request - WARNING - Forbidden: /listitem/6/
2024-11-10 10:52:51,228 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:52:51,702 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:52:53,876 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:52:54,106 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:53:09,548 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:53:10,004 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:54:30,179 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:54:30,625 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:54:33,888 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 10:54:34,243 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:55:04,770 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 10:55:27,005 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:55:27,083 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:55:46,762 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 10:55:46,828 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 10:55:46,829 - django.request - WARNING - Forbidden: /listitem/6/
2024-11-10 11:02:54,875 - django.utils.autoreload - INFO - /Users/coralingber/Desktop/untitled folder 2/lista/backend/base/views.py changed, reloading.
2024-11-10 11:02:55,341 - django.utils.autoreload - INFO - Watching for file changes with StatReloader
2024-11-10 11:04:37,374 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:04:37,579 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:04:47,233 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:04:47,237 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 11:04:47,238 - django.request - WARNING - Forbidden: /listitem/3/
2024-11-10 11:04:47,268 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:04:59,783 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:04:59,788 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 11:04:59,789 - django.request - WARNING - Forbidden: /listitem/4/
2024-11-10 11:04:59,824 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:05:41,905 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:05:41,912 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 11:05:41,917 - django.request - WARNING - Forbidden: /listitem/6/
2024-11-10 11:05:41,953 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:08:33,002 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:08:33,018 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 11:08:33,019 - django.request - WARNING - Forbidden: /listitem/3/
2024-11-10 11:13:57,641 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:13:57,723 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:02,179 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:02,183 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:02,229 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:07,165 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:07,170 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:07,211 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:23,425 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:23,437 - application_logger - ERROR - Error in perform_update: User not logged in. | User ID: 123 | Object ID: 456
2024-11-10 11:14:23,438 - django.request - WARNING - Forbidden: /listitem/5/
2024-11-10 11:14:54,776 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:54,833 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:59,039 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:59,043 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:14:59,072 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:09,720 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:09,725 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:09,757 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:25,405 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:25,410 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:25,474 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:15:46,359 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:10,126 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:10,218 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:28,552 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:28,619 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:34,224 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:34,228 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:34,263 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:38,663 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:38,667 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:18:38,691 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:24:30,678 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:24:30,684 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 11:24:30,807 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:05:22,066 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:05:22,164 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:11,315 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:11,402 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:16,918 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:16,923 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:16,956 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:06:56,640 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:10:15,997 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:10:16,078 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:10:19,333 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:11:39,196 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:11:39,261 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:01,831 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:01,889 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:08,662 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:32,088 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:32,096 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:12:32,170 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:17:39,150 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:17:39,229 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:02,506 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:02,552 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:02,655 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:31,402 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:31,414 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:31,481 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:48,382 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:48,386 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:18:48,429 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:10,501 - application_logger - INFO - Function get_token executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:10,589 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:17,338 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:17,344 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:17,387 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:38,938 - application_logger - INFO - Function perform_create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:39,011 - application_logger - INFO - Function create executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:39,096 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:53,119 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:53,126 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:25:53,177 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:04,245 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:04,251 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:04,300 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:22,300 - application_logger - INFO - Function get_queryset executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:22,305 - application_logger - INFO - Function perform_update executed successfully in views.py | User ID: 123 | Object ID: 456
2024-11-10 12:26:22,343 - application_logger - INFO - Function list_by_user executed successfully in views.py | User ID: 123 | Object ID: 456
